CREATE SCHEMA ELECTRONICS_STORE;
CREATE TABLE ELECTRONICS_STORE.EMPLOYEE
	(EmployeeID		BIGINT		NOT NULL,
	 Password		VARCHAR(30)  NOT NULL,
	 FirstName		VARCHAR(15)	 NOT NULL,
	 LastName		VARCHAR(15)   NOT NULL,
	 Title			VARCHAR(15),
	 Supervisor		BIGINT,
PRIMARY KEY (EmployeeID));

CREATE TABLE ELECTRONICS_STORE.CUSTOMER
	(Email		VARCHAR(35)		 NOT NULL,
	 PhoneNumber BIGINT,
	 FirstName		VARCHAR(25)	  NOT NULL,
	 MiddleInitial		CHAR(1) ,
	 LastName		VARCHAR(25)   NOT NULL,
	 Street			VARCHAR(35)    NOT NULL,
	 City			VARCHAR(15)    NOT NULL,
	 State			CHAR(2)        NOT NULL,
	 ZipCode		VARCHAR(5)     NOT NULL,
PRIMARY KEY (Email));

CREATE TABLE ELECTRONICS_STORE.SECTION
	(SectionID		BIGINT		NOT NULL,
	Name			VARCHAR(15)  NOT NULL,
	Description		VARCHAR(50),  
PRIMARY KEY (SectionID));

CREATE TABLE ELECTRONICS_STORE.DEVICES
	(ItemNumber		BIGINT		NOT NULL,
	 SKUNumber		BIGINT		NOT NULL,
	 Name			VARCHAR(30),
	 Brand			VARCHAR(30),
	 Type			VARCHAR(15), 
	 SectionID		BIGINT,
	 Stock			BIGINT,
PRIMARY KEY (ItemNumber),
CONSTRAINT FOREIGN KEY (SectionID) REFERENCES SECTION(SectionID));

CREATE TABLE ELECTRONICS_STORE.ORDERS
	(OrderNumber	BIGINT		          NOT NULL,
	 Date			DATE	          NOT NULL,
	 Total			DECIMAL	          NOT NULL,
	 EmployeeID		BIGINT		          NOT NULL,
	 Email          VARCHAR(35)        NOT NULL,
	 ItemNumber		BIGINT		NOT NULL,	
PRIMARY KEY (OrderNumber),
FOREIGN KEY (ItemNumber) REFERENCES DEVICES(ItemNumber) ON DELETE CASCADE,
FOREIGN KEY (Email) REFERENCES CUSTOMER(Email) ON DELETE CASCADE,
FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID) ON DELETE CASCADE);

CREATE TABLE ELECTRONICS_STORE.COMPRISES
	(ItemNumber		BIGINT		NOT NULL,	
	 SectionID		BIGINT		NOT NULL,
PRIMARY KEY (ItemNumber, SectionID),
FOREIGN KEY (ItemNumber) REFERENCES DEVICES(ItemNumber) ON DELETE CASCADE,
FOREIGN KEY (SectionID) REFERENCES SECTION(SectionID) ON DELETE CASCADE);

CREATE TABLE ELECTRONICS_STORE.MANAGES
	(EmployeeID		BIGINT		NOT NULL,
	 SectionID		BIGINT		NOT NULL,
PRIMARY KEY (EmployeeID, SectionID),
FOREIGN KEY (EmployeeID) REFERENCES EMPLOYEE(EmployeeID) ON DELETE CASCADE,
FOREIGN KEY (SectionID) REFERENCES SECTION(SectionID) ON DELETE CASCADE);

CREATE TABLE ELECTRONICS_STORE.HAS
	(OrderNumber	BIGINT	             NOT NULL,
	 ItemNumber		BIGINT		NOT NULL,
PRIMARY KEY (OrderNumber, ItemNumber),
FOREIGN KEY (OrderNumber) REFERENCES ORDERS(OrderNumber) ON DELETE CASCADE,
FOREIGN KEY (ItemNumber) REFERENCES DEVICES(ItemNumber) ON DELETE CASCADE);
